# Generated by Django 5.0.3 on 2024-05-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='image',
            field=models.ImageField(default='', upload_to='portfolio/media/img/'),
        ),
        migrations.AlterField(
            model_name='index',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/media/pdf/'),
        ),
    ]
