# Generated by Django 5.0.3 on 2024-05-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_index_image_alter_index_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='link1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='link1',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link2',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
