# Generated by Django 5.0.3 on 2024-05-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_index_link1_alter_projects_link1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
