# Generated by Django 5.0.3 on 2024-05-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projects_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='skills',
            name='color',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='skills',
            name='icon',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
