# Generated by Django 5.0.3 on 2024-05-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_projects_name_alter_skills_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.TextField(default='')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
