# Generated by Django 5.0.3 on 2024-05-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link1',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link2',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
