# Generated by Django 5.0.3 on 2024-05-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_projects_link1_alter_projects_link2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='image',
            field=models.ImageField(default='', upload_to='media/img/'),
        ),
        migrations.AlterField(
            model_name='index',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media/pdf/'),
        ),
    ]
